In [1]:
# Import libraries
import pandas as pd
import numpy as np
import nltk
import re

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

# Download nltk resources (run once)
nltk.download('punkt')
nltk.download('stopwords')

# Load dataset
df = pd.read_csv("MachineLearning.csv")

# Display dataset
df.head()

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,created_utc,score,domain,id,title,author,ups,downs,num_comments,permalink,...,over_18,thumbnail,subreddit_id,edited,link_flair_css_class,author_flair_css_class,is_self,name,url,distinguished
0,1.375240e+09,139,self.MachineLearning,1jeawf,Machine Learning Books,ilsunil,156,17,36,http://www.reddit.com/r/MachineLearning/commen...,...,False,self,t5_2r3gv,1375317761.0,NaN,NaN,True,t3_1jeawf,http://www.reddit.com/r/MachineLearning/commen...,NaN
1,1.324929e+09,129,cs.cmu.edu,nre76,We are the 99%.,gatr1126,153,24,7,http://www.reddit.com/r/MachineLearning/commen...,...,False,http://f.thumbs.redditmedia.com/oSMHyr5B0tJS4-...,t5_2r3gv,False,NaN,NaN,False,t3_nre76,http://www.cs.cmu.edu/~bsettles/assets/svm.jpg,NaN
2,1.359246e+09,129,peekaboo-vision.blogspot.de,17cbuz,Machine Learning Cheat Sheet (for scikit-learn),Tafkas,148,19,20,http://www.reddit.com/r/MachineLearning/commen...,...,False,http://f.thumbs.redditmedia.com/-CqSzm_oV7AWmB...,t5_2r3gv,False,NaN,NaN,False,t3_17cbuz,http://peekaboo-vision.blogspot.de/2013/01/mac...,NaN
3,1.367089e+09,117,self.MachineLearning,1d899i,Google have this week been granted a very broa...,ohell,137,20,46,http://www.reddit.com/r/MachineLearning/commen...,...,False,self,t5_2r3gv,1367100629.0,NaN,NaN,True,t3_1d899i,http://www.reddit.com/r/MachineLearning/commen...,NaN
4,1.351490e+09,114,fora.tv,129gsx,Peter Norvig reveals new developments by Googl...,Ahdoes,120,6,8,http://www.reddit.com/r/MachineLearning/commen...,...,False,http://c.thumbs.redditmedia.com/VP4MXqVgFCHZcs...,t5_2r3gv,False,NaN,NaN,False,t3_129gsx,http://fora.tv/2012/10/14/Peter_Norvig_Channel...,NaN

In [4]:
print(df.columns)

Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')

In [7]:


df.head()

,created_utc,score,domain,id,title,author,ups,downs,num_comments,permalink,...,over_18,thumbnail,subreddit_id,edited,link_flair_css_class,author_flair_css_class,is_self,name,url,distinguished
0,1.375240e+09,139,self.MachineLearning,1jeawf,Machine Learning Books,ilsunil,156,17,36,http://www.reddit.com/r/MachineLearning/commen...,...,False,self,t5_2r3gv,1375317761.0,NaN,NaN,True,t3_1jeawf,http://www.reddit.com/r/MachineLearning/commen...,NaN
1,1.324929e+09,129,cs.cmu.edu,nre76,We are the 99%.,gatr1126,153,24,7,http://www.reddit.com/r/MachineLearning/commen...,...,False,http://f.thumbs.redditmedia.com/oSMHyr5B0tJS4-...,t5_2r3gv,False,NaN,NaN,False,t3_nre76,http://www.cs.cmu.edu/~bsettles/assets/svm.jpg,NaN
2,1.359246e+09,129,peekaboo-vision.blogspot.de,17cbuz,Machine Learning Cheat Sheet (for scikit-learn),Tafkas,148,19,20,http://www.reddit.com/r/MachineLearning/commen...,...,False,http://f.thumbs.redditmedia.com/-CqSzm_oV7AWmB...,t5_2r3gv,False,NaN,NaN,False,t3_17cbuz,http://peekaboo-vision.blogspot.de/2013/01/mac...,NaN
3,1.367089e+09,117,self.MachineLearning,1d899i,Google have this week been granted a very broa...,ohell,137,20,46,http://www.reddit.com/r/MachineLearning/commen...,...,False,self,t5_2r3gv,1367100629.0,NaN,NaN,True,t3_1d899i,http://www.reddit.com/r/MachineLearning/commen...,NaN
4,1.351490e+09,114,fora.tv,129gsx,Peter Norvig reveals new developments by Googl...,Ahdoes,120,6,8,http://www.reddit.com/r/MachineLearning/commen...,...,False,http://c.thumbs.redditmedia.com/VP4MXqVgFCHZcs...,t5_2r3gv,False,NaN,NaN,False,t3_129gsx,http://fora.tv/2012/10/14/Peter_Norvig_Channel...,NaN

In [9]:


df.head()

,created_utc,score,domain,id,title,author,ups,downs,num_comments,permalink,...,over_18,thumbnail,subreddit_id,edited,link_flair_css_class,author_flair_css_class,is_self,name,url,distinguished
0,1.375240e+09,139,self.MachineLearning,1jeawf,Machine Learning Books,ilsunil,156,17,36,http://www.reddit.com/r/MachineLearning/commen...,...,False,self,t5_2r3gv,1375317761.0,NaN,NaN,True,t3_1jeawf,http://www.reddit.com/r/MachineLearning/commen...,NaN
1,1.324929e+09,129,cs.cmu.edu,nre76,We are the 99%.,gatr1126,153,24,7,http://www.reddit.com/r/MachineLearning/commen...,...,False,http://f.thumbs.redditmedia.com/oSMHyr5B0tJS4-...,t5_2r3gv,False,NaN,NaN,False,t3_nre76,http://www.cs.cmu.edu/~bsettles/assets/svm.jpg,NaN
2,1.359246e+09,129,peekaboo-vision.blogspot.de,17cbuz,Machine Learning Cheat Sheet (for scikit-learn),Tafkas,148,19,20,http://www.reddit.com/r/MachineLearning/commen...,...,False,http://f.thumbs.redditmedia.com/-CqSzm_oV7AWmB...,t5_2r3gv,False,NaN,NaN,False,t3_17cbuz,http://peekaboo-vision.blogspot.de/2013/01/mac...,NaN
3,1.367089e+09,117,self.MachineLearning,1d899i,Google have this week been granted a very broa...,ohell,137,20,46,http://www.reddit.com/r/MachineLearning/commen...,...,False,self,t5_2r3gv,1367100629.0,NaN,NaN,True,t3_1d899i,http://www.reddit.com/r/MachineLearning/commen...,NaN
4,1.351490e+09,114,fora.tv,129gsx,Peter Norvig reveals new developments by Googl...,Ahdoes,120,6,8,http://www.reddit.com/r/MachineLearning/commen...,...,False,http://c.thumbs.redditmedia.com/VP4MXqVgFCHZcs...,t5_2r3gv,False,NaN,NaN,False,t3_129gsx,http://fora.tv/2012/10/14/Peter_Norvig_Channel...,NaN

In [11]:
print(df.columns)

Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')

In [13]:
df.columns

Index(['created_utc', 'score', 'domain', 'id', 'title', 'author', 'ups',
       'downs', 'num_comments', 'permalink', 'selftext', 'link_flair_text',
       'over_18', 'thumbnail', 'subreddit_id', 'edited',
       'link_flair_css_class', 'author_flair_css_class', 'is_self', 'name',
       'url', 'distinguished'],
      dtype='str')